package com.obstrom.todolistservice.service;

import com.obstrom.todolistservice.dto.UserRequestDto;
import com.obstrom.todolistservice.model.User;
import com.obstrom.todolistservice.repository.UserRepository;
import com.obstrom.todolistservice.utility.AppUtility;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;

@Service
public class UserService {

    private final UserRepository userRepository;

    @Autowired
    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public List<User> findAllUser() {
        Iterable<User> iterable = userRepository.findAll();
        return AppUtility.convertIterableToList(iterable);
    }

    public User findUserById(String userId) {
        // TODO - Add exception and handler
        return userRepository.findById(userId)
                .orElseThrow(() -> new IllegalArgumentException(String.format("No user with ID '%s' found", userId)));
    }

    public User findUserByUsername(String username) {
        // TODO - Implement repository method
        return null;
    }

    public User createNewUser(UserRequestDto userDto) {
        // TODO - Add role with security

        // TODO - Add validation

        // Build user
        User newUser = User.builder()
                .id(null) // generated by database
                .createdAt(new Date())
                .username(userDto.username())
                .password(userDto.password())
                .build();

        return userRepository.save(newUser);
    }

    public void deleteUser(String userId) {
        userRepository.delete(findUserById(userId));
    }

}
