package com.obstrom.todolistservice.service;

import com.obstrom.todolistservice.error.exception.EntityNotFoundException;
import com.obstrom.todolistservice.error.exception.UniqueFieldConstraintException;
import com.obstrom.todolistservice.model.User;
import com.obstrom.todolistservice.repository.UserRepository;
import com.obstrom.todolistservice.security.UserRole;
import com.obstrom.todolistservice.utility.AppUtility;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;

@Service
public class UserService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Autowired
    public UserService(UserRepository userRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    public List<User> findAllUsers() {
        Iterable<User> iterable = userRepository.findAll();
        return AppUtility.convertIterableToList(iterable);
    }

    public User findUserById(String userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new EntityNotFoundException(String.format("No user with ID '%s' found", userId)));
    }

    public User findUserByUsername(String username) {
        return userRepository.findUserByUsername(username)
                .orElseThrow(() -> new EntityNotFoundException(String.format("No user with username '%s' found", username)));
    }

    public User createNewUser(String username, String password) {
        return registerUser(username, password, UserRole.ROLE_USER);
    }

    public User createNewAdminUser(String username, String password) {
        return registerUser(username, password, UserRole.ROLE_ADMIN);
    }

    public void deleteUser(String userId) {
        userRepository.delete(findUserById(userId));
    }

    private User registerUser(String username, String password, UserRole role) {
        // Validate new user
        if (userRepository.findUserByUsername(username).isPresent())
            throw new UniqueFieldConstraintException(String.format("Username '%s' is already taken", username));

        // Build user
        User newUser = User.builder()
                .id(null) // generated by database
                .createdAt(new Date())
                .username(username)
                .password(passwordEncoder.encode(password))
                .role(role)
                .build();

        return userRepository.save(newUser);
    }

}
